# Site settings
title: Karl Bowden
email: karl@karlbowden.com
description: > # this means to ignore newlines until "baseurl:"
  Brute force engineer. King of Karlsbadia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://karlbowden.com" # the base hostname & protocol for your site
twitter_username: karlbowden
github_username:  agentk

# Build settings
markdown: kramdown
permalink: /:categories/:title/

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: /:title/