# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: karlbowden.com
email: karl@karlbowden.com
description: > # this means to ignore newlines until "baseurl:"
  Karl Bowden, King of Karlsbadia
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://karlbowden.com" # the base hostname & protocol for your site
permalink: /:title/
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'bs-config.js']


#Plugins
gems:
  - jekyll-sitemap
  - redcarpet


# Markdown Rendering
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions:
    - tables
    - autolink
    - strikethrough
    - space_after_headers
    - with_toc_data
    - fenced_code_blocks
    - no_intra_emphasis
    - footnotes
    - smart

